### ISSUE TITLE
Generator namespace

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#116]
Create new namespace for "Generator" which will hold pages for each version of MediaWiki. Use [Property:Has generator](https://wikiapiary.com/wiki/Property:Has_generator) as the key property to drive new pages. Need to create Template:Generator and Form:Generator. This can be used to aggregate data on versions of MediaWiki in use.

**Comment by jthingelstad** [comment]
Generator namespace created.

**Comment by plexish** [comment]
Ideas for possible properties beyond release date and website count:
Number of extensions known to be compatible with this version (shows up at least once in version matrix)+Link to the SMW query which gives the list
URL to release notes
Time between previous/next releases of the engine and this one?
Average age of sites using this version?
Average no. of extensions on sites using this extension?

And if you're not already planning to, I'd love to see time-series data for website count at least.

**Comment by jthingelstad** [comment]
This is largely stubbed out. Need to let jobs finish before allowing to create pages automatically. Noting that there is a lot that is in Template:Farm that can be applied to Template:Generator.

**Comment by jthingelstad** [comment]
Still a ton more to do on this, but I’m going to consider this in for now. You can see

https://wikiapiary.com/wiki/Category:Generator

Shows 115 versions of MediaWiki currently in use on WikiApiary.
