### ISSUE TITLE
Bulk import of mediawikis_2013_byothers

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#122]
Wikiteam [shared this list of wikis](https://groups.google.com/forum/#!topic/wikiteam-discuss/erRTEk2RpLU) they found and cleaned up.

> mediawikis_2013_byothers.txt has been checked and filtered and uploaded as:
> mediawikis_2013_byothers-alive.txt
> 11,232 URLs

This should be imported in WikiApiary.

**Comment by jthingelstad** [comment]
This import is completed. I had to restart the loader a couple of times so the import count was a bit fragmented, but a simple query shows **983 websites** created today. Interesting to note that this file had 11,232 lines so only **8.75%** of the wikis listed were working with an API **and** unknown to WikiApiary. I suspect that the net gain from bulk loads will continue to diminish as the number of wikis in WikiApiary gets larger.

**Comment by nemobis** [comment]
Great! I'm glad this was useful for WikiApiary as well.
As you already import the wikis we make dumps of, should I expect those 983 wikis are all missing a dump?

Note, we also have another list made more or less from the same source, with some more URLs. https://code.google.com/p/wikiteam/source/browse/trunk/listsofwikis/mediawikis_2013_checked.txt
