### ISSUE TITLE
Expanding content namespaces

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#129]
I am not sure if the new namespace "generator" was added to the array of  [`$wgContentNamespaces`](https://www.mediawiki.org/wiki/Manual:$wgNamespacesWithSubpages). The other extra namespaces like "extension" and "skin" could be double checked, too.

**Comment by jthingelstad** [comment]
Confirming all is good.

```
$wgContentNamespaces[] = NS_GENERATOR;
$wgNamespacesToBeSearchedDefault[NS_GENERATOR] = true;
```
