### ISSUE TITLE
Updating the DataTransfer extension

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#138]
I am desperately trying to upload pages however the file header gets rejected all the time though it works perfect on my test wiki. Since the I18n of the installed version is completely broken I cannot see why the file is rejected. Current master of this extension is a rectified version.

**Comment by jthingelstad** [comment]
Updated.

`Updating 9b78e5b..124849d`

Close if this fixes or helps the issue. What are you trying to upload? Which pages?

**Comment by kghbln** [comment]
Missing generators. It's easier to prepare a file than adding them individually.

**Comment by kghbln** [comment]
Works like charm now and the wiki has 77 new generators :) Thank you!

**Comment by jthingelstad** [comment]
Excellent.
