### ISSUE TITLE
"Special:Contact" broken and needs to be reconfigured

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#148]
[Special:Contact](https://wikiapiary.com/wiki/Special:Contact) needs to be reconfigured to work with the 2.x versions of the [ContactPage extension](https://www.mediawiki.org/wiki/Extension:ContactPage#Version_.E2.89.A5_2.x_.28MediaWiki_.E2.89.A5_1.23.29). Basically it is just a copy and paste of the new code provided with small adaptions.

**Comment by jthingelstad** [comment]
This is **finally** fixed.
