### ISSUE TITLE
Make Template:Website guess Special:Statistics URL

### ISSUE THREAD

**Issue by plexish** [WikiApiary/WikiApiary#150]
It should be possible to guess the Special:Statistics URL with some regex based on the main page URL, and get it right in a vast majority of cases (alternate language wikis seem to redirect to the correct place), with override possible if a site has it in an odd place. If we want to start collecting from Special:Statistics more (as will happen when #54 is done), it would be handy to have it pre-populated.

**Comment by jthingelstad** [comment]
I don't want to do that in a template  Audit Bee could do this during the audit process though.

**Comment by plexish** [comment]
Okay, that works too. New bug or edit this?
