### ISSUE TITLE
Rename main pages

### ISSUE THREAD

**Issue by plexish** [WikiApiary/WikiApiary#153]
I think we'd be better off moving Extension:Main Page to Extension:Extensions, Skin:Main Page to Skin:Skins, Farm:Main Page to Farm:Farms, and Generator:Main Page to Generator:Generators (plus finish creating Websites to give a better intro with a bunch more stats than the current category page or main page). Redirects should be kept imo.

With the namespace hidden in the title, each one has the same displayed name as the others, and it's not super informative. Differentiating the names like this seems like a positive step to me, but maybe there's some reason to keep current or some better alternate naming system I'm missing.
- [x] Post this to see if you guys like the idea
- [x] Move pages
- [x] Improve, finish, and fix [Websites](https://wikiapiary.com/wiki/Websites)
- [x] Edit Mediawiki:Sidebar to point at new locations (needs admin powers)

**Comment by kghbln** [comment]
I am a bit indifferent about moving e.g. "Exension:Main_Page" to "Extension:Extensions", probably because for me on Fx and O I get the namespace name eg. "Extension" and not "Main_Page". So there is no big reason from my point of view I guess.

**Comment by plexish** [comment]
hm.. it looks different from how I remember it, now main pages show no text as heading, where I think they has Main Page before... I should check things better before making bugs. I'll withdraw this.

**Comment by plexish** [comment]
Doing this since thingles said he liked the idea in the other bug.

**Comment by plexish** [comment]
And all done. [Websites](https://wikiapiary.com/wiki/Websites) could still use a bit of work, but it's an improvement over the category page as-is.
