### ISSUE TITLE
Build "Special:Properties" via cron

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#157]
I think it will impact performance if "Special:Properties" is updated using the  [RebuildPropertyStatistics.php](https://semantic-mediawiki.org/wiki/Help:RebuildPropertyStatistics.php) script.

**Comment by nischayn22** [comment]
Can you explain how this will impact performance?

**Comment by kghbln** [comment]
Well this page takes about 3 to 5 seconds to render on WikiAPIary. Depending on the traffic this page gets it will be good to serve the data from cache. Let's use the power to generate this page for some other stuff.

**Comment by nischayn22** [comment]
I think there is some caching. @mwjames might know better.

**Comment by mwjames** [comment]
Caching settings for `Special:Properties`, `Special:WantedProperties`, `Special:UnusedProperties`, and `Special:Statistics` can be found [here](https://github.com/SemanticMediaWiki/SemanticMediaWiki/blob/master/SemanticMediaWiki.settings.php#L539).

`RebuildPropertyStatistics` doesn't purge the cache and would only be relevant to the display of data in `Special:Statistics` (currently the expiry is based on a time factory).

**Comment by nischayn22** [comment]
@mwjames can the cache be purged by providing an argument in the URL?

**Comment by kghbln** [comment]
Well, I have totally misunderstood the purpose of this script. I understood that this one was solely for "Special:Properties" to facilitate a miser mode style behaviour for it. I must have had very senior moments when addig this to the wiki - ouch! Well this issue should be turned into a 3600 \* 24 thing. :)

**Comment by jthingelstad** [comment]
So after reviewing this it looks like this should be closed as a `wontfix` yes?

**Comment by kghbln** [comment]
In case you would like to keep the cache at 1 hour, yes. A day however will imho be enough of goodness here. Up to you.
