### ISSUE TITLE
FuzzyBot should be FuzzyBee

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#166]
There is a bot that updates pages to match new version of source page. It is by default called FuzzyBot. On WikiAPIary it should consistently be FuzzyBee. Thus `$wgTranslateFuzzyBotName = 'FuzzyBee';` needs to be added to "LocalSettings.php"

@thingles Another Bee :)

**Comment by kghbln** [comment]
Oops, `$wgTranslateFuzzyBotName = 'Fuzzy Bee';`

**Comment by jthingelstad** [comment]
Added.

Where does this show up?

**Comment by kghbln** [comment]
As soon as the source page gets updated and the new updated version of the text is approved "Fuzzy Bee" will sync all available translations to match the new version of the source page. Translaters will then know that they will have to do new translations for an already translated page.

**Comment by kghbln** [comment]
@thingles Forgot all about it. Fuzzy Bee should be marked as a bot.

**Comment by jthingelstad** [comment]
[Done](https://wikiapiary.com/w/index.php?title=Special%3ALog&type=rights&user=&page=User%3AFuzzy+Bee&year=&month=-1)

**Comment by kghbln** [comment]
Thank you!
