### ISSUE TITLE
Add Host tagline

### ISSUE THREAD

**Issue by plexish** [WikiApiary/WikiApiary#167]
https://wikiapiary.com/wiki/MediaWiki:Tagline should have a line for hosts.

**Comment by kghbln** [comment]
[Done](https://wikiapiary.com/w/index.php?title=MediaWiki%3ATagline&diff=1067316&oldid=1065588)

**Comment by kghbln** [comment]
I probably prematurely closed this: @thingles should check if Worker Bee is able to update this line, too after its insertion.

**Comment by jthingelstad** [comment]
Ugh. Worker Bee is currently dumb with how he updates. The intent is to have it auto-update those values but needs #108 and the v2 of the bots to get in production. For now I should probably just disable his automatic updates. @kghbln was doing a better job.

I've commented out the UpdateTagline method in worker bee for now so human edits will remain. I also reverted to @kghbln last edit.
