### ISSUE TITLE
Show default skin on website template

### ISSUE THREAD

**Issue by plexish** [WikiApiary/WikiApiary#174]
Cavila pointed out on Website's talk page that default skin is not shown.

**Comment by jthingelstad** [comment]
This starts to get into #64 a little bit. The default and skipped flags are shown on the Skins subpage, see [WikiApiary/Skins](https://wikiapiary.com/wiki/WikiApiary/Skins). This is all part of my conclusion that the Web site page itself cannot show everything (I'd like to see the tabs go away) and that the subpages themselves can be used to show detailed information for a given website.

The issue brought up here is an interesting one. Probably the most interesting thing to put on the main Web site page is what the default skin is and the count of skins installed. Other than that, other skin details could be left to the subpage template to display with a link from the Web site page.

**Comment by plexish** [comment]
Yep, when we do that redesign I agree that most of the information should move to /Skins. On sites which we don't have a default skin for a list of skins would probably be a good idea, but normally default/count would be fine.

Until then, probably a good idea to have default displayed.
