### ISSUE TITLE
Create new property for extensions for MediaWiki.org name

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#179]
This will be used by @apexkid to map an extension to where it lives on MW.org. If not present, it can be guessed by looking at the extension URL. Having a separate property will allow us to override when needed, and make it much easier to manage.

**Comment by apexkid** [comment]
Created new property and modified Form:Extension. 
https://wikiapiary.com/wiki/Property:Has_mediawiki_url
Had some doubts into how to modify Template:Extension as it already contains Property:URL and will be redundant with Mediawiki URL in most cases. Please look into it.

**Comment by jthingelstad** [comment]
I don't think you want a URL. I would simply have a property for "Has MediaWiki.org page title" that is the title inside the Extension namespace for the extension.

**Comment by jthingelstad** [comment]
Actually, it looks like I already have a property that does this. See https://wikiapiary.com/wiki/Property:Has_MediaWiki.org_title. You should just use that. Your logic should first check if title is defined and if it is do a direct page call to that title. If not, attempt to use the URL but making sure it is a URL on MediaWiki.org.

**Comment by jthingelstad** [comment]
This already existed at `Property:Has MediaWiki.org title`.
