### ISSUE TITLE
Orain farm task

### ISSUE THREAD

**Issue by plexish** [WikiApiary/WikiApiary#186]
We've got 60 Orain farm wikis, but are missing ~100. The majority of the ones we're missing are closed (41) or private (22), but it'd be nice to keep up to date. I tidied up the ones [hosted on unusual urls](https://github.com/Orain/ansible-playbook/blob/master/roles/mediawiki/files/localsettings/LocalSettings.php.j2#l1164), the rest can be found [here](https://meta.orain.org/wiki/Database_list).

**Comment by jthingelstad** [comment]
_Moved to WikiApiary/FarmerBee#1._
