### ISSUE TITLE
Figure out what to do with SourceForge duplicates

### ISSUE THREAD

**Issue by plexish** [WikiApiary/WikiApiary#189]
There are [a lot of them](https://wikiapiary.com/wiki/Concept:Duplicate_website/SourceForge), and I'm not sure exactly what's happening. The wikis don't seem to be easy to find, maybe not accessible at all.

All the links I've found so far just redirect to the project's page, maybe defuncting a large number is the best way to go?

**Comment by jthingelstad** [comment]
What makes you say these are duplicates? They don't seem to be duplicates to me.

**Comment by plexish** [comment]
They're auto-marked as duplicates due to having exactly the same edit count and founded date. I'm going to expand the check to include article and pages count which should reduce the false positives significantly.

**Comment by jthingelstad** [comment]
This check is getting really expensive. I think we need to consider having duplicate checking be part of the audit process. Then we can have Python code do some really sophisticated stuff and not slow down Template:Website.

**Comment by plexish** [comment]
Okay, if this is moving to the bots I'm not going to be much help right now so I've unassigned myself from #74.

**Comment by jthingelstad** [comment]
Closing. This concept no longer shows any pages. Not clear what action if any is needed.
