### ISSUE TITLE
Website form: problem with IDNA URLs

### ISSUE THREAD

**Issue by ciencia** [WikiApiary/WikiApiary#195]
There's a problem with the Website form or SMW for the URL parameter when the domain name contains non-ascii characters (IDNA) [1]: https://wikiapiary.com/w/index.php?oldid=1135013

Clicking the link goes to nowhere! (on Firefox at least)

If I paste the same URL on a normal page, or out of the form, the link can be opened without problems.

Apparently, the server part of the URL is being URLEncoded or percent-encoded, and that doesn't seem to be right.

---

[1] http://en.wikipedia.org/wiki/Internationalized_domain_name

**Comment by plexish** [comment]
Good find, this seems to be an issue with SMW. Example [here](https://wikiapiary.com/wiki/User:Ete/International_URL_issue).

Edit, wait, no. Not SMW. It's happening directly in mediawiki too.

Edit2: Actually, this happens even if you copy the url directly to the bar. And in Chrome too. I think maybe some characters don't work properly directly in the address bar?

**Comment by ciencia** [comment]
The URL works fine for me if I copy and paste it directly in the address bar.

In your example, if you view the generated HTML, the [[Has URL:: ]] link is percent-encoded (and doesn't work), while the normal one isn't (which works). Yeah, it seems a SMW issue

**Comment by jthingelstad** [comment]
Is it possible that SemanticMediaWiki/SemanticMediaWiki#633 fixes this?

**Comment by ciencia** [comment]
This issue seems to have been fixed in the meantime
