### ISSUE TITLE
Adapt group permissions for users and editors (move)

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#200]
``` php
$wgGroupPermissions['user']['move'] = false;
$wgGroupPermissions['editor']['move'] = true;
$wgGroupPermissions['editor']['suppressredirect'] = true;
```

Probably a better option because of [this discussion](https://wikiapiary.com/wiki/WikiApiary_talk:Handling_duplicate_names#Moving_website_pages)

**Comment by jthingelstad** [comment]
Now that [wiki-farm](https://github.com/thingles/wiki-farm) is here you could do a pull request for this. :-) (Totally kidding, don't need to do that. `:-P`)

**Comment by kghbln** [comment]
I still had to. I thought that you called the edtitor group "editor" and not "editors". The latter approach is better anyway but this needed this small adaption. Hmm... the formatting in the diff is quite awkward but when looking at it in the editor it looks ok. :|
