### ISSUE TITLE
Spam protection currently challanged

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#204]
Today WikiAPIary got ["heaps" of new registrations](https://wikiapiary.com/wiki/Special:Log/newusers) from what I believe will be spammers. They have not gotten to the point of actually spamming stuff to the wiki, however there is something in the water.

**Comment by kghbln** [comment]
@thingles The spam account creation is currently accelerating. No spam so far, but I think it needs attention at his point.

**Comment by jthingelstad** [comment]
@kghbln thanks for the note. I’m currently pretty intrigued by [TextCaptcha](http://textcaptcha.com/how_it_works). It is in the spirit of what I did previously, but much broader. I’m using it on [Ask Planet Kubb](http://ask.planetkubb.com) using [q2a-logical-captcha](https://github.com/amiyasahu/q2a-logical-captcha). Wish there was a MediaWiki implementation but don't see one out there.

**Comment by jthingelstad** [comment]
Okay, I finally put in a different dynamic test. This one now asks questions like:

> What is the sixth digit of the number nine hundred fifty-one million eight hundred ninety-eight thousand four hundred twenty-seven?

I did limited testing and it works. I’m hoping this proves pretty effective. It will require spammers (and humans) to reverse the english for the number.

**Comment by jthingelstad** [comment]
As an FYI, a few weeks ago I automated removeUnusedAccounts and it runs weekly now. That is the reason for the sawtooth in this chart. Will be curious to see if the new captcha gets this back to the quiet we had before.

![users](https://cloud.githubusercontent.com/assets/5351/4802508/391d520a-5e45-11e4-98f4-d9f8cbbe9451.png)

**Comment by jthingelstad** [comment]
Blog post at http://thingelstad.com/updated-dynamic-questy-captchas/.
