### ISSUE TITLE
Mediawiki:Sidebar navigation not showing up

### ISSUE THREAD

**Issue by plexish** [WikiApiary/WikiApiary#205]
No recent changes here: https://wikiapiary.com/wiki/MediaWiki:Sidebar so I'm not sure what's happening.

**Comment by jthingelstad** [comment]
I’m not entirely sure why but redis had stopped running on me. Redis holds the PHP sessions and MediaWiki cache. This also stopped anyone from being able to login. I restarted redis and it all started working fine. I’m not sure why redis died and why it wasn't restarted automatically by upstart. 

Resolved for now but cause unknown.
