### ISSUE TITLE
Fix lack of CSS on login screen

### ISSUE THREAD

**Issue by hexmode** [WikiApiary/WikiApiary#207]
The login screen has a black header instead of a yellow one because MediaWiki:Common.{js,css} are not loaded any more on Special:Login and Special:Preferences.  This was due to a recent fix in MediaWiki to block user's CSS and JS.

The fix is https://gerrit.wikimedia.org/r/#/c/165979/ -- a change I hope to release in 1.24.

**Comment by hexmode** [comment]
https://lists.wikimedia.org/pipermail/wikitech-l/2014-November/079309.html

**Comment by kghbln** [comment]
@hexmode You are a hero for me and so is @Legoktm. :star2: All these troubles with the communities and now we are regaining paradise soon. :) Legoktm has authored backports for the [1.22](https://gerrit.wikimedia.org/r/#/c/174014/), [1.23](https://gerrit.wikimedia.org/r/#/c/174014/) and [1.24](https://gerrit.wikimedia.org/r/#/c/174012/) branches. As soon as they are in Wikiapiary will also be fluffy even if staying on 1.23

**Comment by jthingelstad** [comment]
Okay, @hexmode I’m a little rusty. How do I just happy this one change to WikiApiary? I’m thinking I probably should not upgrade to 1.24-rc2 yet? WikiApiary is running 1.23.6 right now, and I run the tarball.

**Comment by legoktm** [comment]
You can get a patch file from gerrit for the 1.23 cherry-pick I've proposed: https://gerrit.wikimedia.org/r/changes/174014/revisions/f9c0a427bee70e3ec47cee9f53bdb8ca60f23d6a/patch?zip (for https://gerrit.wikimedia.org/r/#/c/174014/)

**Comment by jthingelstad** [comment]
@legoktm thank you!

@hexmode confirmed this patch does what you think it does. Applied on WikiApiary right now. See [login page](https://wikiapiary.com/w/index.php?title=Special:UserLogin&returnto=Main+Page).
