### ISSUE TITLE
Display of UNIQ12f3a863336f17a8-nowiki-00000002-QINU

### ISSUE THREAD

**Issue by mwjames** [WikiApiary/WikiApiary#210]
[0] shows various lines of `UNIQ12f3a863336f17a8-nowiki-00000002-QINU`.

@s7eph4n Probably relates to a change on how SF / MW 1.24 use the Parser (see also #209). [1] reported a similar issue in connection with SF.

[0] https://wikiapiary.com/wiki/ArchaeoWiki
[1] http://wikimedia.7.x6.nabble.com/Semantic-Form-Inputs-Datepicker-Issue-tp5039468p5039751.html

**Comment by s7eph4n** [comment]
I think/hope I fixed that issue in the latest commit uploaded just now.

**Comment by kghbln** [comment]
This issue is around for quite some time now so I do not think that it relates to the MW 1.24 upgrade. This was discussed but I cannot remember where. However the latest code changes could have fixed this issue anyway. I will report if I see it around again.

**Comment by mwjames** [comment]
Now and then still appears on some pages but closing this issue for now.
