### ISSUE TITLE
Weird drop in edit counts for nowiki

### ISSUE THREAD

**Issue by Ironholds** [WikiApiary/WikiApiary#213]
See [this](https://wikiapiary.com/wiki/Wikipedia_%28no%29#chart3): any idea what happened? I'd hope that if our servers had dropped a million edits instantaneously, we would've noticed.

**Comment by Ironholds** [comment]
Looks like a core error. Will have someone patch.

**Comment by hexmode** [comment]
Could you point to what you think is the cause?

**Comment by Ironholds** [comment]
@hexmode [pertinent phabricator thread](https://phabricator.wikimedia.org/T76356): the only thing I can think of is that the Special:Statistics entry was wrong. Not only did I check the dbs, I iterated through the XML dumps...nothing except for WikiApiary and Special:Stats' previous version supports the 14m number. It's tremendously weird.

**Comment by jthingelstad** [comment]
Hello @Ironholds. Sorry for the delay in looking at this, busy week. I did comment on [T76356](https://phabricator.wikimedia.org/T76356#823694) as well so you can reach me as needed.

**Comment by Ironholds** [comment]
@thingles that's okay; the commentary is most appreciated! :)
