### ISSUE TITLE
Clicking "save page" produces error: Invalid or virtual namespace -1 given.

### ISSUE THREAD

**Issue by hexmode** [WikiApiary/WikiApiary#216]
Adding the wiki using this link results in the error:

https://wikiapiary.com/wiki/Special:FormEdit/Website?Website[URL]=http%3A%2F%2Fwww.fastar.org%2Fwiki%2Findex.php%3Ftitle%3DMain_Page&Website[API+URL]=&Website[Name]=Main+Page+-+fastarWiki&Website[Description]=

**Comment by hexmode** [comment]
https://wikiapiary.com/wiki/Special:FormEdit/Website?Website[URL]=http%3A%2F%2Fwiki.dpconline.org%2Findex.php%3Ftitle%3DMain_Page&Website[API+URL]=http%3A%2F%2Fwiki.dpconline.org%2Fapi.php&Website[Name]=wiki.dpconline.org&Website[Description]=

**Comment by jthingelstad** [comment]
I have no idea. Looking now. See multiple references to "Invalid or virtual namespace" in Phabricator. I’m getting pretty frustrated with upgrading lately. Seems every upgrade brings problems. Ugh.

**Comment by jthingelstad** [comment]
Alright. Phabricator shows this issue with a bunch of extensions. It pointed the finger at Cite and I tried rolling that back to no benefit. [T78645](https://phabricator.wikimedia.org/T78645) pointed finger at ConfirmEdit. I moved from `master` to `REL1_24` branch on ConfirmEdit and the URL's you listed above are now able to save right.

Not sure what the root is.
