### ISSUE TITLE
Server certificate expired

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#220]
The server certificate expired today and should be renewed. Already two cool years of Wikiapiary have passed.

**Comment by jthingelstad** [comment]
Thanks. I think I'll be able to renew it today.

**Comment by jthingelstad** [comment]
Certificate updated.

**Comment by jthingelstad** [comment]
Also finally disabled SSLv3 and now only support TLS.

**Comment by kghbln** [comment]
Great. I just checked with Qualys and Wikiapiary got an A :+1:
