### ISSUE TITLE
"open chart in new window" no longer working properly

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#229]
When clicking "open chart in new window" to view the data an new window gets opened by nothing is shown. This happens with FF 36+ due to the fact that mixed contend is automatically blocked due to "dygraph-combined.js" (http://wikiapiary.com/apiary/lib/dygraph-combined.js) being loaded via http.

**Comment by jthingelstad** [comment]
Found the reference and changed it to https. @kghbln can you confirm if this is resolved?

**Comment by kghbln** [comment]
Affirmative. All up and fluffy. :) Thanks!
