### ISSUE TITLE
Create WikiApiary extension to get contributions from closed wikis

### ISSUE THREAD

**Issue by hexmode** [WikiApiary/WikiApiary#232]
During a discussion with @peterwoudsma here at SMWCon, he suggested that there would be an interest in creating an extension so that closed wikis (firewalled, etc) would have an interest in contributing their meta information (users over time, pages over time, changes, etc) while keeping their wiki content private.

This would help us build the community of enterprise users, demonstrate the usefulness of MediaWiki for Enterprise knowledge sharing, and help increase attendance at gatherings like SMWCon.

This could be done using an extension that would push metadata to an endpoint on WikiApiary.  Or, um, email updates.

There would have to be some verification (email address) and probably a good way to verify contribuions (an emailed token that the user would put in LocalSettings?)

**Comment by hexmode** [comment]
[Planned group discussion](http://semantic-mediawiki.org/wiki/SMWCon_Spring_2015/Discussions/Registration_of_Protected_Wikis_on_Wikiapiary)

**Comment by jthingelstad** [comment]
#22 is a very similar related story. There are a number of wikis that are public, but require a login since `readapi` is denied for anonymous users. I've thought for a long time that Bumble Bee could actually login and then issue it’s requests. There just needs to be a way to set a username, then generate a password and send it to the right user.

Of course this still requires that the wiki be accessible. If there was some desire to put a wiki that was _not_ publicly accessible at all (intranet wiki) an extension could be make to post the data to WikiApiary via another means.

**Comment by peterwoudsma** [comment]
One solution is to give WikiApiary access to the protected wiki's and that goes against the protection settings... Once in the wiki, WikiApiary can harvest the authorized metadata, and much more than that. Even if you find a way to control the level of access, the affected organizations will still be reluctant to share through this procedure, and there may even be security regulations against it.

I am in favor of a solution that would push metadata to WikiApiary, in whatever format this is suitable for further processing. This can be made possible with some programming, and likely incorporating the code in a "PushToWikiApiary" extension. Organizations would make an active and conscientious decision to push that metadata to WikiApiary, recognizing the benefits of matching their own wiki to compareable wiki installations.

Any other suggestions?

**Comment by jthingelstad** [comment]
There is a repo already for HoneyBee, which is intended to be a future MediaWiki extension that works with WikiApiary. I added WikiApiary/HoneyBee#6 for tracking this. I’m going to close this issue as further work and conversation should happen on that issue.
