### ISSUE TITLE
Update python to 2.7.11

### ISSUE THREAD

**Issue by paladox** [WikiApiary/WikiApiary#237]
Hi please could you update python to 2.7.11 on https://wikiapiary.com/wiki/ please?

Since I am getting ssl errors here https://wikiapiary.com/wiki/Random_Wikisaur

2016-08-27 06:41:14 (info normal) <urlopen error [Errno 1] _ssl.c:510: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error> link

I'm using cloudflare.

http://stackoverflow.com/questions/34513784/urlopen-error-errno-1-ssl-c510-error14077417ssl

**Comment by paladox** [comment]
@thingles @kghbln I'm wondering could you update the servers python to 2.7.11 to see if it fixes the ssl issue please? Since others may use cloudflare thus stopping there wiki from being tracked.

**Comment by jthingelstad** [comment]
The SysAdmin functions for WikiApiary have been handed off from me to the MediaWiki Stakeholders group headed up via @hexmode. I think folks are still figuring out how to go forward with the Unix level stuff.

**Comment by paladox** [comment]
@thingles oh would you be able to ask @hexmode to update the server python please since this is a problem for users using cloudflare?

**Comment by paladox** [comment]
We only need the server upgraded for python, this may fix many https errors :)

**Comment by hexmode** [comment]
The server is running [Ubuntu Trusty](http://packages.ubuntu.com/search?keywords=python).  The StackOverflow question seems to say that python 2.9 is sufficient.  2.9 is available in Ubuntu Wiley. Would that be ok?

**Comment by paladox** [comment]
Yes please. I guess that will work. @hexmode could you install python 2.9 to see if that fixes thing please :)

**Comment by hexmode** [comment]
Since it looks fairly easy to upgrade to the next LTS (easier than getting one package from wiley) I'm trying that. If this works, you'll have 2.7.11

**Comment by paladox** [comment]
@hexmode thanks :)

Are you doing that now?

**Comment by hexmode** [comment]
That's a good way to waste half a day.  But now I am more familiar with how @thingles set up the system.

Python is upgraded, but so is wikiapiary.

File new bugs for anything you find.

**Comment by paladox** [comment]
@hexmode thankyou :)

**Comment by paladox** [comment]
@hexmode it seems the errors have gone now, but the bumble bee bot is till not updating the information about my site and I'm not sure why https://wikiapiary.com/wiki/Random_Wikisaur

I'm running mw 1.28 wmf 17 but https://wikiapiary.com/wiki/Random_Wikisaur says I'm running 1.27 wmf 23

**Comment by kghbln** [comment]
> I'm running mw 1.28 wmf 17 but https://wikiapiary.com/wiki/Random_Wikisaur says I'm running 1.27 wmf 23

@paladox As you can see BumbleBee started to collect statistical data again so I believe it is working. Please allow some time for AuditBee and BumbleBee to fly out and return to the apiary with new data.

**Comment by paladox** [comment]
ok thanks.

**Comment by hexmode** [comment]
It shows "MediaWiki Version     Generator:MediaWiki 1.28.0-wmf.17 (1.28.0-wmf.17)" now

**Comment by paladox** [comment]
Yep thanks.

Thankyou for fixing the problem :)
