### ISSUE TITLE
Not working counters

### ISSUE THREAD

**Issue by kuznet1** [WikiApiary/WikiApiary#239]
For example, see https://wikiapiary.com/wiki/Tradingview_Wiki

**Comment by kghbln** [comment]
That appears to be an issue with your wiki https://www.tradingview.com/wiki/static/api.php?action=query&meta=siteinfo&siprop=statistics Perhaps BumbleBee could be adapted to provide the requested info if possible. I have now changed to collection via Special:Statistics. Let's see what happens.

**Comment by kghbln** [comment]
I see that the issue was indeed with the wiki itself. Working now.

**Comment by kuznet1** [comment]
Thanks for help, this issue was caused by invalid settings of AWS Extension, it can be fixed by [this](https://www.mediawiki.org/wiki/Topic:So9qs2u9svb3j4gx)

**Comment by kghbln** [comment]
Great, thanks for reporting back!
