### ISSUE TITLE
Server certificate expired

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#240]
The server certificate used for WikiApiary.com expired today (2017-01-03) and needs to be replaced.

**Comment by kghbln** [comment]
Ah, cool! Already switched to Let's Encrypt in the meantime. Thanks a lot @hexmode !

**Comment by hexmode** [comment]
I was bombarded with email this morning.

**Comment by kghbln** [comment]
> I was bombarded with email this morning.

Poor you and I even added to this. :(

**Comment by kghbln** [comment]
It however proves that people actually care about the wiki which is a great thing.

**Comment by hexmode** [comment]
I wish I could say the email was from people.  That /would/ be awesome.

However, the bots are much quicker to notice problems and don't know that one (or ten) emails is enough.

**Comment by kghbln** [comment]
Ah, so back to just me. But there are others around too how appreciate WikiApiary, too.
