### ISSUE TITLE
Invalid SSL certificate for wikiapiary

### ISSUE THREAD

**Issue by FO-nTTaX** [WikiApiary/WikiApiary#243]
The server currently serves a certificate that is only valid for the wl.wikiapiary.com subdomain, so the site is inaccessible unless one puts a security exception. See https://wikiapiary.com/

**Comment by revi** [comment]
I think Wikimedia Phabricator is better monitored these days... [T192226](https://phabricator.wikimedia.org/T192226)

**Comment by FO-nTTaX** [comment]
Ah I wasn't aware of that
