### ISSUE TITLE
Chats displaying statistical informatin stopped working

### ISSUE THREAD

**Issue by kghbln** [WikiApiary/WikiApiary#244]
Since November 11, 2018 the charts displaying statistical information on the respective wiki's activity are no longer working, meaning that no more data is displayed. Unsure if the collection has an issue or the mechanism turning the collected data into visualization.

Originally reported on the [mailing list](https://lists.wikimedia.org/pipermail/wikiapiary/2018-December/000030.html)

**Comment by jdvorak001** [comment]
The site I am responsible for, https://wikiapiary.com/wiki/Sociologick%C3%A1_encyklopedie, is still reported to run on Mediawiki 1.27. However, I upgraded it to 1.31 on the critical date of 2018-11-11 at 16:38 CET (that was the time I switched the symlink). I'll try to get hold of access logs.

**Comment by ciencia** [comment]
My site's access logs stopped getting requests from Wikiapiary bot at around that time, and still not getting any request.

**Comment by hexmode** [comment]
I logged in and found that the cron jobs were not running.  This *appeared* to be a permissions problem on the file (`/etc/cron.d/bees` had permissions of 600 instead of 644).

This came about because of the changes that were done to the VM by cloud services.

You can see from [the logs](https://wikiapiary.com/wiki/WikiApiary:Bot_log) that it is running but there appears to still be a problem in that only one site is being crawled per segment.

**Comment by ciencia** [comment]
Probably it errors when processing the first website, aborting the job but reporting 1 as processed.

**Comment by xloem** [comment]
Has this been resolved? Is there anything others could do to help resolve it?

**Comment by ciencia** [comment]
It works for me, and access logs on my website shows data is being collected. In fact, statistics on Wikiapiary are updated as well. Any particular website you're having problems with?

**Comment by xloem** [comment]
hexmode had said

> there appears to still be a problem in that only one site is being crawled per segment

and the issue was still open, so i was just checking.  when i visited the repository and website they looked unmaintained.  it's great to learn that isn't the case!
