### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by xloem** [WikiApiary/WikiApiary#245]
Is anybody still around?  I see the host is still running despite server errors for two years =)

Would anybody be interested in setting up automation, so the community can continue to maintain this system?  For example, is [automatic merging of pull requests](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request) enabled?

**Comment by hexmode** [comment]
Yes, we still maintain the site.  If you see server errors, please report them.

There haven't been that many pull requests, and there is no test suite, so automatic merging doesn't make much sense, does it?

**Comment by xloem** [comment]
If maintaining ever becomes unmanageable, automatic merging of pull requests, even without a testsuite (you could set it up to wait for community review still), would help visitors be able to contribute contribute when they can.
