### ISSUE TITLE
Statistics on front page not working (showing 0)

### ISSUE THREAD

**Issue by ineffyble** [WikiApiary/WikiApiary#252]
Screenshot:

![image](https://user-images.githubusercontent.com/834880/132112134-ebebe033-06ae-402a-9945-13e55c149433.png)

**Comment by kghbln** [comment]
I am on this site frequently but I did not notice this. Talking about being routine-blinded. Thanks for reporting.

**Comment by kghbln** [comment]
I basically removed some statistics that were not shown anyways and we got the old main page with working stats etc. Good.
