### ISSUE TITLE
Pull composer.json from Wikis to track composer usage

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#31]
Retrieve composer.json from wikis at the well known URL (server + scriptpath + "/composer.json")

http://semantic-mediawiki.org/w/composer.json

Add flag for wikis that are using composer and potentially other information retrieved from the file. Would it be worthwhile to grab the require statements or would they simply tell me the same thing as the extensions installed? (Which makes me wonder if I should have a new property for extensions for their composer require name?) Would it be worth tracking the “minimum-stability” setting for a given wiki?

**Comment by JeroenDeDauw** [comment]
composer.josn tells you the version ranges of what needs to be installed. Not the actual versions of what is installed, including the dependencies and whatnot.

http://semantic-mediawiki.org/w/composer.lock

I am however unsure if those files are supposed to be publicly accessible. This is scary http://semantic-mediawiki.org/w/LocalSettings.php

Luckily there is a check in there so our passwords and tokens are not accessible. Still, one should likely not be able to access this at all.

> Would it be worth tracking the “minimum-stability” setting for a given wiki?

I don't think so.

I posted this a while back on the SMW user list:

Have an API module that simply serves the composer.lock file. This can be implemented as trivially as reading the file and serving that, or perhaps doing a json parse in between and feeding the array to the MW API thing. In fact, I'd not go further and add additional things on top here, so it stays as simple as it can be for this use case. And if it is this trivial, it might be feasible to get it into MW core.

Be warned, whoever implements this might be forever loved by Jamie Thingelstad (Wikiapiary).

**Comment by jthingelstad** [comment]
Love the comment on the list, I missed that message. :-)

So, it seems obvious that extensions need to have a property for package name going forward right?

**Comment by JeroenDeDauw** [comment]
> So, it seems obvious that extensions need to have a property for package name going forward right?

Yeah, else you will not easily be able to make sense of the Composer info. And if you have the package name, you can also link to services such as [Packagist](https://packagist.org/users/Jeroen%20De%20Dauw/) and [VersionEye](https://www.versioneye.com/php/data-values:data-values)

**Comment by jthingelstad** [comment]
Added to from and template. See Composer field here

https://wikiapiary.com/wiki/Extension:Semantic_MediaWiki

Packagist API is easy to query to pull in some additional info.

**Comment by jthingelstad** [comment]
Closing this in favor of #224.
