### ISSUE TITLE
Semantic MediaWiki message "a is not declared as a valid unit" on Template:Website

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#34]
Something is wrong with semantic annotations on Settings tab. Nearly any shows "a is not declared as a valid unit of measurement for this property". "AM", perhaps?

![screenshot](https://f.cloud.github.com/assets/5351/1907487/0c10bc8c-7ccf-11e3-9553-be2a3d9a146b.png)

See [Traditio](http://wikiapiary.com/wiki/Traditio) for example.

**Comment by plexish** [comment]
This is back everywhere, though I'm pretty sure it was not around yesterday. Maybe linked to Redis, since that's the only major recent change which seems potentially relevant?

**Comment by kghbln** [comment]
I have seen this only on selected site, but all the time. Did not investigate further though. :|

**Comment by jthingelstad** [comment]
This issue has been around for a very long time. I've looked at the templates, but it’s not obvious what the issue is. I've sort of just left it and assumed when someone does #64 it probably will just disappear.
