### ISSUE TITLE
Handle API values where empty string = True

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#36]
Note the value for `"misermode": ""`:

https://wikiapiary.com/w/api.php?action=query&meta=siteinfo&siprop=general&format=json

This means "True" for the MediaWiki API. Make sure WikiApiary catches this right.

**Comment by apexkid** [comment]
Please tell which file is this bug related to?

**Comment by jthingelstad** [comment]
This is done in the newest bots.
