### ISSUE TITLE
Integrate it

### ISSUE THREAD

**Issue by suriyaa** [WikiApiary/WikiApiary#38]
Hi,

I wanted to know where she integrates these bots. In "/extensions" or somewhere else?

-Suriyaa Kudo

(PS: I would like to use it for iSC Pedia)

**Comment by jthingelstad** [comment]
Sorry, I don't understand what your asking here. Can you elaborate?

**Comment by suriyaa** [comment]
Yes, I wanted to know where those files are on WikiApiary and I would like to integrate it for my wiki.
