### ISSUE TITLE
Convert wikiteam standalone script to Farm tasks

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#51]
Existing Python script operates as stand alone and scans the entire Internet Archive for Wikiteam each week. This could be invoked more frequently and cache the most recent timestamps to just do incremental updates.

**Comment by nemobis** [comment]
I don't remember if one can also get items sorted by latest update date (rather than just creation date), but https://pypi.python.org/pypi/internetarchive would know.
Let me know if I can help with this script.

**Comment by jthingelstad** [comment]
_Moved to WikiApiary/FarmerBee#8._
