### ISSUE TITLE
Farming task for Wikkii

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#71]
Wikkii shows [list of wikis](http://wikkii.com/wiki/Special:Farmer/list). Create a farmer task to parse this list (use BeautifulSoup4) and insure they are all in WikiApiary.

The original version of this script is at:
https://gist.github.com/thingles/6840d400bd8be41f8d85

**Comment by nemobis** [comment]
Should probably be closed given https://github.com/WikiApiary/WikiApiary/issues/137#issuecomment-48830552

**Comment by plexish** [comment]
Yep, Wikkii seems pretty dead sadly.

**Comment by jthingelstad** [comment]
Sort of the ultimate `wontfix`. :-)
