### ISSUE TITLE
Farming task for ShoutWiki

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#72]
ShoutWiki exposes a [category of all wikis](http://www.shoutwiki.com/wiki/Category:Flat_list_of_all_wikis). This list could be retrieved via the MediaWiki API and then used to sync with WikiApiary.

**Comment by lewiscawte** [comment]
We've talked many times with WikiApiary and related people about a far more effective API module we have for purposes such as this...

**Comment by jthingelstad** [comment]
@lewiscawte that would be me, and I think I remember something. Could you possibly add that API call to this issue so that we have it for when we want to get this done? Thanks.

**Comment by jthingelstad** [comment]
_Moved to WikiApiary/FarmerBee#7._
