### ISSUE TITLE
Allow users to comment on extensions

### ISSUE THREAD

**Issue by jthingelstad** [WikiApiary/WikiApiary#87]
I would like to have users comment on extensions. The [Comments](https://mediawiki.org/wiki/Extension:Comments) extension looks good for this. I’m also strongly considering using Disqus via a Widget.

Whatever is done for this could be done for Skins as well.

It would be nice to be able to at least have a comment count as a property of the Extension.

**Comment by plexish** [comment]
Would be cool. I'm somewhat in favor of avoiding third party dependencies, but Disqus would give a prettier system.

**Comment by jthingelstad** [comment]
I've added a [Disqus widget](https://wikiapiary.com/wiki/Widget:DISQUS) to [websites](https://wikiapiary.com/wiki/Template:Website), [extensions](https://wikiapiary.com/wiki/Template:Extension), [farms](https://wikiapiary.com/wiki/Template:Farm) and [skins](https://wikiapiary.com/wiki/Template:Skin). I investigated the [Disqus API](https://disqus.com/api/docs/) and it is robust. I could easily have a bot task that syndicated certain Disqus data (comment count, star count, etc) into the templates on WikiApiary so that they can be combined with the rest of the data.

**Comment by kghbln** [comment]
Were is currently a GSoC project underway that is aiming at adding ratings to extensions. I wonder if this would allow for comments, too. If yes, wouldn't this be some kind of duplication?

**Comment by hexmode** [comment]
It could be duplication if done wrong.  It could be that @apexkid could just use Disqus ratings and comments and focus on the syndication of that data to MW.o.

Pinging him for comment on this.  Looks like if we let Disqus handle the vote counting it solves a few problems.

**Comment by hexmode** [comment]
btw, left a comment on the disqus widget's talk page.  There is a problem with getting unsecured content when you're on a secure page.

**Comment by kghbln** [comment]
I was just about to investigate this issue, since I discovered it, too. Just fixed this and everything is fluffy now. Thanks!

**Comment by jthingelstad** [comment]
Thanks for fixing @kghbln!
